<template>
  <div class="order-form-container">
    <!-- Form Header -->
    <div class="form-header">
      <div class="header-content">
        <div class="header-info">
          <h2 class="form-title">
            {{ formMode === 'add' ? $t('addNewOrder') : $t('editOrder') }}
          </h2>
          <p class="form-subtitle">
            {{ formMode === 'add' ? $t('createNewOrderDescription') : $t('updateOrderDescription') }}
          </p>
        </div>
        <div class="header-actions">
          <Button 
            :label="$t('preview')" 
            icon="pi pi-eye" 
            severity="secondary" 
            outlined 
            @click="previewOrder"
            :disabled="!order.customer"
          />
          <Button 
            :label="$t('saveAsDraft')" 
            icon="pi pi-save" 
            severity="secondary" 
            outlined 
            @click="saveAsDraft"
            :loading="draftLoading"
          />
        </div>
      </div>
      <!-- Progress Indicator -->
      <div class="form-progress">
        <div class="progress-bar">
          <div class="progress-fill" :style="{ width: `${formProgress}%` }"></div>
        </div>
        <span class="progress-text">{{ Math.round(formProgress) }}% {{ $t('complete') }}</span>
      </div>
    </div>

    <!-- Main Form Content -->
    <div class="form-content">
      <TabView v-model:activeIndex="activeTab" class="order-tabs" @tab-change="onTabChange">
        <!-- Basic Information Tab -->
        <TabPanel :header="$t('basicInfo')" class="tab-panel">
          <div class="tab-content">
            <div class="section-header">
              <h3 class="section-title">{{ $t('orderDetails') }}</h3>
              <p class="section-description">{{ $t('basicOrderInformation') }}</p>
            </div>
            
            <div class="form-grid">
              <!-- Order Number -->
              <div class="form-field" :class="{ 'field-error': v$.orderNumber.$error }">
                <label for="orderNumber" class="field-label required">
                  {{ $t('orderNumber') }}
                  <Tooltip target=".orderNumber-help" :value="$t('orderNumberTooltip')" position="top" />
                  <i class="pi pi-question-circle orderNumber-help help-icon"></i>
                </label>
                <InputText
                  id="orderNumber"
                  v-model="localOrder.orderNumber"
                  :class="{ 'p-invalid': v$.orderNumber.$error }"
                  :placeholder="$t('autoGenerated')"
                  @blur="v$.orderNumber.$touch"
                  @input="updateProgress"
                  maxlength="50"
                  class="field-input"
                  :disabled="formMode === 'add'"
                />
                <div class="field-footer">
                  <small v-if="v$.orderNumber.$error" class="error-message">
                    {{ v$.orderNumber.$errors[0].$message }}
                  </small>
                  <small class="char-counter">
                    {{ localOrder.orderNumber?.length || 0 }}/50
                  </small>
                </div>
              </div>

              <!-- Customer -->
              <div class="form-field" :class="{ 'field-error': v$.customer.$error }">
                <label for="customer" class="field-label required">
                  {{ $t('customer') }}
                  <Tooltip target=".customer-help" :value="$t('customerTooltip')" position="top" />
                  <i class="pi pi-question-circle customer-help help-icon"></i>
                </label>
                <AutoComplete
                  id="customer"
                  v-model="localOrder.customer"
                  :suggestions="customerSuggestions"
                  @complete="searchCustomers"
                  :placeholder="$t('selectCustomer')"
                  field="name"
                  class="field-input"
                  @input="updateProgress"
                  @blur="v$.customer.$touch"
                />
                <small v-if="v$.customer.$error" class="error-message">
                  {{ v$.customer.$errors[0].$message }}
                </small>
              </div>

              <!-- Order Date -->
              <div class="form-field">
                <label for="date" class="field-label required">
                  {{ $t('orderDate') }}
                </label>
                <Calendar
                  id="date"
                  v-model="localOrder.date"
                  :showIcon="true"
                  dateFormat="yy-mm-dd"
                  :placeholder="$t('selectDate')"
                  class="field-input"
                  @change="updateProgress"
                />
              </div>

              <!-- Status -->
              <div class="form-field">
                <label for="status" class="field-label required">
                  {{ $t('status') }}
                </label>
                <Dropdown
                  id="status"
                  v-model="localOrder.status"
                  :options="statusOptions"
                  optionLabel="label"
                  optionValue="value"
                  :placeholder="$t('selectStatus')"
                  class="field-input"
                  @change="updateProgress"
                />
              </div>

              <!-- Total -->
              <div class="form-field">
                <label for="total" class="field-label required">
                  {{ $t('total') }}
                  <Tooltip target=".total-help" :value="$t('totalTooltip')" position="top" />
                  <i class="pi pi-question-circle total-help help-icon"></i>
                </label>
                <div class="input-group">
                  <span class="input-addon">TND</span>
                  <InputNumber
                    id="total"
                    v-model="localOrder.total"
                    :placeholder="$t('enterTotal')"
                    :min="0"
                    :maxFractionDigits="2"
                    class="field-input"
                    @input="updateProgress"
                  />
                </div>
              </div>
            </div>
          </div>
        </TabPanel>

        <!-- Order Items Tab -->
        <TabPanel :header="$t('orderItems')" class="tab-panel">
          <div class="tab-content">
            <div class="section-header">
              <h3 class="section-title">{{ $t('orderItems') }}</h3>
              <p class="section-description">{{ $t('manageOrderItems') }}</p>
            </div>

            <div class="form-grid">
              <div class="form-field full-width">
                <div class="items-header">
                  <h4 class="items-title">{{ $t('items') }}</h4>
                  <Button 
                    :label="$t('addItem')" 
                    icon="pi pi-plus" 
                    size="small"
                    @click="addItem"
                  />
                </div>
                
                <DataTable 
                  :value="localOrder.items" 
                  editMode="cell" 
                  @cell-edit-complete="onCellEditComplete" class="items-table"
                  responsiveLayout="scroll"
                  v-if="localOrder.items && localOrder.items.length > 0"
                >
                  <Column field="name" :header="$t('productName')" style="width: 40%">
                    <template #editor="{ data, field }">
                      <InputText v-model="data[field]" />
                    </template>
                  </Column>
                  <Column field="quantity" :header="$t('quantity')" style="width: 20%">
                    <template #editor="{ data, field }">
                      <InputNumber v-model="data[field]" :min="1" />
                    </template>
                  </Column>
                  <Column field="price" :header="$t('price')" style="width: 20%">
                    <template #editor="{ data, field }">
                      <InputNumber v-model="data[field]" :min="0" :maxFractionDigits="2" />
                    </template>
                  </Column>
                  <Column style="width: 20%">
                    <template #header>
                      <span>{{ $t('actions') }}</span>
                    </template>
                    <template #body="{ index }">
                      <Button 
                        icon="pi pi-trash" 
                        severity="danger"
                        text
                        rounded
                        @click="removeItem(index)"
                      />
                    </template>
                  </Column>
                </DataTable>
                
                <div v-else class="empty-items">
                  <p class="empty-text">{{ $t('noItemsYet') }}</p>
                </div>
              </div>
            </div>
          </div>
        </TabPanel>

        <!-- Shipping Address Tab -->
        <TabPanel :header="$t('shippingAddress')" class="tab-panel">
          <div class="tab-content">
            <div class="section-header">
              <h3 class="section-title">{{ $t('shippingAddress') }}</h3>
              <p class="section-description">{{ $t('shippingDetails') }}</p>
            </div>

            <div class="form-grid">
              <!-- Street Address -->
              <div class="form-field full-width">
                <label for="street" class="field-label">{{ $t('streetAddress') }}</label>
                <InputText
                  id="street"
                  v-model="localOrder.shippingAddress.street"
                  :placeholder="$t('enterStreetAddress')"
                  @input="updateProgress"
                  class="field-input"
                />
              </div>

              <!-- City -->
              <div class="form-field">
                <label for="city" class="field-label">{{ $t('city') }}</label>
                <InputText
                  id="city"
                  v-model="localOrder.shippingAddress.city"
                  :placeholder="$t('enterCity')"
                  @input="updateProgress"
                  class="field-input"
                />
              </div>

              <!-- Postal Code -->
              <div class="form-field">
                <label for="postalCode" class="field-label">{{ $t('postalCode') }}</label>
                <InputText
                  id="postalCode"
                  v-model="localOrder.shippingAddress.postalCode"
                  :placeholder="$t('enterPostalCode')"
                  @input="updateProgress"
                  class="field-input"
                />
              </div>

              <!-- Country -->
              <div class="form-field">
                <label for="country" class="field-label">{{ $t('country') }}</label>
                <AutoComplete
                  id="country"
                  v-model="localOrder.shippingAddress.country"
                  :suggestions="filteredCountries"
                  @complete="searchCountries"
                  :placeholder="$t('selectCountry')"
                  class="field-input"
                  @input="updateProgress"
                />
              </div>
            </div>
          </div>
        </TabPanel>

        <!-- Notes Tab -->
        <TabPanel :header="$t('notes')" class="tab-panel">
          <div class="tab-content">
            <div class="section-header">
              <h3 class="section-title">{{ $t('notes') }}</h3>
              <p class="section-description">{{ $t('orderNotes') }}</p>
            </div>

            <div class="form-grid">
              <!-- Notes -->
              <div class="form-field full-width">
                <label class="field-label">{{ $t('notes') }}</label>
                <Textarea
                  v-model="localOrder.notes"
                  :placeholder="$t('enterNotes')"
                  rows="5"
                  class="field-input"
                  @input="updateProgress"
                />
              </div>
            </div>
          </div>
        </TabPanel>
      </TabView>
    </div>

    <!-- Form Actions -->
    <div class="form-actions">
      <div class="actions-left">
        <Button 
          :label="$t('cancel')" 
          icon="pi pi-times" 
          severity="secondary"
          outlined 
          @click="handleCancel"
        />
      </div>
      <div class="actions-right">
        <Button 
          :label="$t('saveAndAddAnother')" 
          icon="pi pi-plus" 
          severity="secondary"
          outlined 
          @click="saveAndAddAnother"
          :loading="saveAndAddLoading"
        />
        <Button 
          :label="$t('save')" 
          icon="pi pi-check" 
          @click="validateAndSave"
          :loading="saveLoading"
          class="save-button"
        />
      </div>
    </div>

    <!-- Unsaved Changes Dialog -->
    <Dialog 
      v-model:visible="showUnsavedDialog" 
      :header="$t('unsavedChanges')"
      :modal="true"
      :closable="false"
      style="width: 400px"
    >
      <p>{{ $t('unsavedChangesMessage') }}</p>
      <template #footer>
        <Button 
          :label="$t('discard')" 
          icon="pi pi-times" 
          severity="secondary"
          outlined 
          @click="discardChanges"
        />
        <Button 
          :label="$t('saveChanges')" 
          icon="pi pi-check" 
          @click="saveBeforeLeave"
          autofocus
        />
      </template>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import { useI18n } from 'vue-i18n'
import { useVuelidate } from '@vuelidate/core'
import { required, maxLength } from '@vuelidate/validators'
import { useCustomerStore } from '@/stores/customerStore'

// Components
import TabView from 'primevue/tabview'
import TabPanel from 'primevue/tabpanel'
import InputText from 'primevue/inputtext'
import InputNumber from 'primevue/inputnumber'
import Calendar from 'primevue/calendar'
import Dropdown from 'primevue/dropdown'
import AutoComplete from 'primevue/autocomplete'
import Button from 'primevue/button'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Dialog from 'primevue/dialog'
import Textarea from 'primevue/textarea'
import Tooltip from 'primevue/tooltip'

// Props & Emits
const props = defineProps({
  order: { type: Object, default: () => ({}) },
  mode: { type: String, default: 'add' },
  loading: { type: Boolean, default: false }
})

const emit = defineEmits(['save', 'cancel', 'save-and-add'])

// Composables
const { t } = useI18n()
const customerStore = useCustomerStore()

// Reactive Data
const activeTab = ref(0)
const localOrder = ref(initializeOrder())
const showUnsavedDialog = ref(false)
const hasUnsavedChanges = ref(false)
const saveLoading = ref(false)
const saveAndAddLoading = ref(false)
const draftLoading = ref(false)
const customerSuggestions = ref([])
const filteredCountries = ref([])

// Form validation rules
const rules = {
  orderNumber: { maxLength: maxLength(50) },
  customer: { required },
  status: { required },
  total: { required }
}

const v$ = useVuelidate(rules, localOrder)

// Options
const statusOptions = [
  { label: t('pending'), value: 'Pending' },
  { label: t('fulfilled'), value: 'Fulfilled' },
  { label: t('cancelled'), value: 'Cancelled' }
]

const countryOptions = [
  'Tunisia', 'France', 'United States', 'Canada', 'Germany', 'United Kingdom'
]

// Computed Properties
const formMode = computed(() => props.mode)

const formProgress = computed(() => {
  let progress = 0
  const fields = [
    localOrder.value.orderNumber,
    localOrder.value.customer,
    localOrder.value.status,
    localOrder.value.total,
    localOrder.value.date
  ]
  
  progress += fields.filter(field => field && field !== '').length * 15
  
  if (localOrder.value.items.length > 0) progress += 10
  if (localOrder.value.shippingAddress.street) progress += 5
  if (localOrder.value.shippingAddress.city) progress += 5
  if (localOrder.value.shippingAddress.postalCode) progress += 5
  if (localOrder.value.shippingAddress.country) progress += 5
  if (localOrder.value.notes) progress += 10
  
  return Math.min(progress, 100)
})

// Methods
function initializeOrder() {
  return {
    id: null,
    orderNumber: '',
    customer: '',
    date: new Date().toISOString(),
    total: 0.0,
    status: 'Pending',
    items: [],
    shippingAddress: {
      street: '',
      city: '',
      postalCode: '',
      country: ''
    },
    notes: '',
    ...props.order
  }
}

function updateProgress() {
  // Progress is handled by computed property
}

function previewOrder() {
  console.log('Preview order:', localOrder.value)
}

async function saveAsDraft() {
  draftLoading.value = true
  try {
    localOrder.value.status = 'Pending'
    await validateAndSave()
  } finally {
    draftLoading.value = false
  }
}

async function validateAndSave() {
  const isValid = await v$.value.$validate()
  if (!isValid) {
    const firstError = v$.value.$errors[0]
    console.error('Validation error:', firstError.$message)
    return
  }

  saveLoading.value = true
  try {
    await emit('save', localOrder.value)
    hasUnsavedChanges.value = false
  } finally {
    saveLoading.value = false
  }
}

async function saveAndAddAnother() {
  saveAndAddLoading.value = true
  try {
    await validateAndSave()
    emit('save-and-add')
    resetForm()
  } finally {
    saveAndAddLoading.value = false
  }
}

function onCellEditComplete(event) {
  let { data, field, newValue, originalEvent: e } = event;

  // Si la nouvelle valeur est valide (non vide pour le nom par exemple)
  // et différente de l'ancienne, on met à jour.
  if (newValue !== null && newValue !== undefined && data[field] !== newValue) {
    data[field] = newValue;
  }
}

function resetForm() {
  localOrder.value = initializeOrder()
  v$.value.$reset()
  activeTab.value = 0
}

function handleCancel() {
  if (hasUnsavedChanges.value) {
    showUnsavedDialog.value = true
  } else {
    emit('cancel')
  }
}

function discardChanges() {
  showUnsavedDialog.value = false
  emit('cancel')
}

async function saveBeforeLeave() {
  showUnsavedDialog.value = false
  await validateAndSave()
  emit('cancel')
}

function searchCustomers(event) {
  const query = event.query.toLowerCase()
  customerSuggestions.value = customerStore.customers.filter(c => 
    c.name.toLowerCase().includes(query) || c.email.toLowerCase().includes(query)
  )
}

function searchCountries(event) {
  filteredCountries.value = countryOptions.filter(country => 
    country.toLowerCase().includes(event.query.toLowerCase())
  )
}

function addItem() {
  if (!localOrder.value.items) {
    localOrder.value.items = []
  }
  localOrder.value.items.push({
    productId: Date.now(),
    name: '',
    quantity: 1,
    price: 0.0
  })
  updateProgress()
}

function removeItem(index) {
  localOrder.value.items.splice(index, 1)
  updateProgress()
}

// Watch for changes
watch(localOrder, () => {
  hasUnsavedChanges.value = true
}, { deep: true })

// Lifecycle Hooks
onMounted(() => {
  window.addEventListener('beforeunload', handleBeforeUnload)
})

onBeforeUnmount(() => {
  window.removeEventListener('beforeunload', handleBeforeUnload)
})

function handleBeforeUnload(e) {
  if (hasUnsavedChanges.value) {
    e.preventDefault()
    e.returnValue = t('unsavedChangesWarning')
    return t('unsavedChangesWarning')
  }
}
</script>

<style scoped>
.order-form-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  background-color: #fff;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.form-header {
  padding: 1.5rem;
  border-bottom: 1px solid #e5e7eb;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.header-info {
  flex: 1;
}

.form-title {
  font-size: 1.5rem;
  font-weight: 600;
  margin: 0 0 0.25rem 0;
  color: #1f2937;
}

.form-subtitle {
  margin: 0;
  color: #6b7280;
  font-size: 0.875rem;
}

.header-actions {
  display: flex;
  gap: 0.75rem;
}

.form-progress {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.progress-bar {
  flex: 1;
  height: 6px;
  background-color: #e5e7eb;
  border-radius: 3px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background-color: #3b82f6;
  transition: width 0.3s ease;
}

.progress-text {
  font-size: 0.875rem;
  color: #6b7280;
}

.form-content {
  flex: 1;
  overflow-y: auto;
  padding: 1.5rem;
}

:deep(.order-tabs) {
  .p-tabview-nav {
    border-bottom: 1px solid #e5e7eb;
  }
  
  .p-tabview-panels {
    padding: 1rem 0;
  }
}

.tab-panel {
  padding: 0;
}

.section-header {
  margin-bottom: 1.5rem;
}

.section-title {
  font-size: 1.125rem;
  font-weight: 600;
  margin: 0 0 0.25rem 0;
  color: #1f2937;
}

.section-description {
  margin: 0;
  color: #6b7280;
  font-size: 0.875rem;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1.5rem;
}

.form-field {
  margin-bottom: 1.25rem;
}

.full-width {
  grid-column: 1 / -1;
}

.field-label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: #374151;
  font-size: 0.875rem;
}

.required:after {
  content: " *";
  color: #ef4444;
}

.help-icon {
  margin-left: 0.25rem;
  color: #9ca3af;
  cursor: help;
}

.field-input {
  width: 100%;
}

.field-footer {
  display: flex;
  justify-content: space-between;
  margin-top: 0.25rem;
}

.error-message {
  color: #ef4444;
  font-size: 0.75rem;
}

.char-counter {
  color: #9ca3af;
  font-size: 0.75rem;
}

.input-group {
  display: flex;
  align-items: center;
}

.input-addon {
  padding: 0.5rem 0.75rem;
  background-color: #f3f4f6;
  border: 1px solid #d1d5db;
  border-right: none;
  border-radius: 4px 0 0 4px;
  font-size: 0.875rem;
  color: #4b5563;
}

.items-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.items-title {
  margin: 0;
  font-size: 1rem;
  color: #1f2937;
}

.empty-items {
  padding: 1.5rem;
  text-align: center;
  border: 1px dashed #d1d5db;
  border-radius: 6px;
  background-color: #f9fafb;
}

.empty-text {
  margin: 0;
  color: #6b7280;
}

:deep(.items-table) {
  .p-datatable-tbody > tr > td {
    padding: 0.5rem;
  }
  
  .p-inputtext, .p-inputnumber {
    width: 100%;
  }
}

.form-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem;
  border-top: 1px solid #e5e7eb;
  background-color: #fff;
}

.actions-left, .actions-right {
  display: flex;
  gap: 0.75rem;
}

.save-button {
  min-width: 120px;
}

/* Responsive */
@media (max-width: 768px) {
  .header-content {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
  }
  
  .header-actions {
    width: 100%;
    justify-content: flex-end;
  }
  
  .form-grid {
    grid-template-columns: 1fr;
  }
  
  .form-actions {
    flex-direction: column-reverse;
    gap: 1rem;
  }
  
  .actions-left, .actions-right {
    width: 100%;
    justify-content: space-between;
  }
}
</style>